//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibet_Autoservice
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Windows.Media;

    public partial class Service
    {
        private decimal newCostValue;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientService = new HashSet<ClientService>();
            this.ServicePhoto = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string MainImagePath { get; set; }
        public int Duration { get; set; }
        public decimal Cost { get; set; }
        public double Discount { get; set; }
        public int DiscountIt
        {
            get
            {
                return (int)(Discount * 100);
            }
            set
            {
                Discount = value / 100.0;
            }
        }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhoto { get; set; }
        public string OldCost
        {
            get
            {
                if (Discount > 0)
                {
                    return Cost.ToString(CultureInfo.InvariantCulture);
                }
                else
                {
                    return "";
                }
            }
        }
        public decimal NewCost
        {
            get
            {
                if (Discount > 0)
                {
                    newCostValue = Cost - Cost * (decimal)Discount;
                    //return ((decimal)Cost - (decimal)Cost * (decimal)Discount / 100);
                }
                else
                {
                    newCostValue = Cost;
                   // return (decimal)Cost;
                }
                return Math.Round(newCostValue, 2);
            }
        }

        public SolidColorBrush FonStyle
        {
            get
            { 
            
                if (Discount > 0)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("LightGreen");
                }
                else
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("White");
                }
            }
        }
    }
}
